### ISSUE TITLE
フォーマット変換時にSwizzleが設定されたテクスチャを正しく扱えない

### ISSUE THREAD

**Issue by eai04191** [Tliks/AutoConfigureTexture#6]
liltoonのSmoothnessに設定するためにSwizzleを 1-R 1-B 1-G A に設定しているテクスチャがあります (1)

これを手動でBC4にすると(2)のようになるはずですが

AutoConfigureTextureのOptimize Texture Formatで変換されたBC4は(3)のようになっていて表現が崩れてしまいます

| 1 | 2 | 3 |
|--------|--------|--------|
| ![](https://github.com/user-attachments/assets/01effb35-b85e-4c22-a31e-663c76003ede) | ![](https://github.com/user-attachments/assets/674acf01-8ce4-429a-b4be-b312a28088ba) | ![](https://github.com/user-attachments/assets/d2ab39ad-e525-4a1c-ab3b-ab222a31ccf1) |

- Auto Configure Texture: 0.2.0
- VRChat SDK - Base: 3.7.3
- このテクスチャが含まれる商品: https://bami3000.booth.pm/items/6318678

**Comment by Tliks** [comment]
報告ありがとうございます。

他のツール(AutoConfigureTextureを含む)がアバター内に存在しない環境において、該当のテクスチャに対してTTT TextureConfiguratorでBC4に変換した際、問題は再現しますか？

**Comment by eai04191** [comment]
一旦AutoConfigureTextureのみの差異で発生していることを確認しました。TextureConfiguratorで発生するか見てみます
<details><summary>Details</summary>

![2024-11-25_20-43-01_Unity](https://github.com/user-attachments/assets/b22b2c64-1d36-4aa0-aa1a-6dcf0099be29)

![2024-11-25_20-44-08_Unity](https://github.com/user-attachments/assets/a4632da4-094a-4587-bcb9-2fc548735160)

</details>

**Comment by eai04191** [comment]
TextureConfiguratorのみで再現することを確認しました
確かに考えてみれば処理自体はTTTがやってるのでこれは関係ないんですね……

TTTの方にissue建ててきます お手数おかけしました

**Comment by eai04191** [comment]
すいません TTTの現時点の最新版0.8.7では再現しない（解消している）ことを確認しました。

このパッケージの依存関係がTTT 0.8.6（か0.9.0-beta.0）を要求していて0.8.7は解決されないので、これを0.8.7（以上？）を解決するように指定すれば解消できそうです

https://github.com/Tliks/AutoConfigureTexture/blob/9d6dddd58f5e54030d7c238657293a1379314cc3/package.json#L16

**Comment by Tliks** [comment]
v0.8.7では確かにテクスチャの圧縮に関する変更が加わっていますが、単体動作する分には影響ない気もするので少し奇妙ですね…
何にせよv0.8.7で解消するとのことなので、次のリリースで依存関係をv0.8.7に変更します(マイグレーションに少々問題がありそうですが、諸々の理由でv0.9.0-beta.0への対応は削除すると思います)

**Comment by Tliks** [comment]
遅くなりましたがv0.2.1にて依存関係をv0.8.7へと変更しました。https://github.com/Tliks/AutoConfigureTexture/blob/7c8e922228441f9dd37d3aa29788eca7016af432/package.json#L16
